// Compiles the Typst resume, copies the PDF into public/, and writes a
// content-hash version file so the website link busts the browser cache
// automatically whenever the resume actually changes.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const src = resolve(root, "resume/Faizal_Razza_Resume.typ");
const out = resolve(root, "resume/Faizal_Razza_Resume.pdf");
const pub = resolve(root, "public/Faizal_Razza_Resume.pdf");
const versionFile = resolve(root, "src/lib/resume-version.ts");

// 1. Compile Typst -> PDF.
// On CI (e.g. Vercel) Typst isn't installed; the committed PDF and
// resume-version.ts are used as-is, so skip compilation gracefully.
const res = spawnSync("typst", ["compile", src, out], { stdio: "inherit" });
if (res.error || res.status !== 0) {
  console.warn("⚠ typst not available — using committed resume PDF/version as-is.");
  process.exit(0);
}

// 2. Copy into public/
copyFileSync(out, pub);

// 3. Hash the PDF and write the version file
const hash = createHash("md5").update(readFileSync(out)).digest("hex").slice(0, 8);
writeFileSync(
  versionFile,
  `// AUTO-GENERATED by scripts/build-resume.ts — do not edit by hand.\nexport const resumeVersion = "${hash}";\n`,
);

console.log(`✓ Resume built — public/Faizal_Razza_Resume.pdf (v=${hash})`);
